# Generated by Django 4.1.4 on 2022-12-12 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosAcademia',
            fields=[
                ('id_medidas', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('dat_medidas', models.DateField()),
                ('altura', models.FloatField(blank=True, null=True)),
                ('peso', models.FloatField(blank=True, null=True)),
                ('imc', models.FloatField(blank=True, null=True)),
                ('gordura', models.FloatField(blank=True, null=True)),
                ('liquido', models.FloatField(blank=True, null=True)),
                ('pa', models.FloatField(blank=True, null=True)),
                ('pulso', models.FloatField(blank=True, null=True)),
                ('bat_cardiaco', models.FloatField(blank=True, null=True)),
                ('quadriceps', models.FloatField(blank=True, null=True)),
                ('torax', models.FloatField(blank=True, null=True)),
                ('cintura', models.FloatField(blank=True, null=True)),
                ('culote', models.FloatField(blank=True, null=True)),
                ('biceps_D', models.FloatField(blank=True, null=True)),
                ('biceps_E', models.FloatField(blank=True, null=True)),
                ('coxa_D', models.FloatField(blank=True, null=True)),
                ('coxa_E', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('aluno_id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('inscricao', models.DateField()),
                ('nome', models.CharField(max_length=50)),
                ('nascimento', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=80)),
                ('rg', models.CharField(max_length=11)),
                ('cpf', models.CharField(max_length=16)),
                ('bairro', models.CharField(max_length=40)),
                ('rua', models.CharField(max_length=80)),
                ('num_residencia', models.CharField(max_length=10)),
                ('dadoscorporais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.dadosacademia')),
            ],
        ),
    ]
