# Generated by Django 4.1.2 on 2022-12-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunos',
            name='id',
        ),
        migrations.AddField(
            model_name='alunos',
            name='divida',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='cpf',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='nascimento',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='dadosacademia',
            name='dat_medidas',
            field=models.CharField(max_length=10),
        ),
    ]
