# Generated by Django 4.1.4 on 2022-12-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunos',
            name='sexo',
        ),
        migrations.AlterField(
            model_name='alunos',
            name='inscricao',
            field=models.DateField(),
        ),
    ]
