# Generated by Django 4.1.4 on 2022-12-15 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='dadoscorporais',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='alunos.dadosacademia'),
        ),
    ]
