# Generated by Django 4.1.4 on 2022-12-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_remove_alunos_id_alunos_divida_alter_alunos_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadosacademia',
            name='dat_medidas',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
